### ISSUE TITLE
Support for cucumber-jvm >= 1.1.3  (so that data tables work)

### ISSUE THREAD

**Issue by jennysivapalan** [skipoleschris/xsbt-cucumber-plugin#26]
Hi,

is it possible to bump up the cucumber version to 1.1.3 for Scala 2.10. This is so that we can use this plugin and data tables (which prior to 1.1.3 did not work). See:

https://github.com/cucumber/cucumber-jvm/issues/443

(This fix was only merged in for 1.1.3.)

Thanks!

**Comment by sebnozzi** [comment]
Same here, would be cool to have it working.

**Comment by skipoleschris** [comment]
Hi. Just to let you know that I'm working on this but just bumping to 1.1.3 has caused my examples to stop working, which probably means something in the plugin is no longer compatible with the latest cucumber version. Hope to have this resolved in the near future.

**Comment by jennysivapalan** [comment]
Thanks -  I forked your project and tried upgrading and writing a test for a dataTable however it didn't seem to work. The same error still occurred with data tables.  You can see what was tried here:-
https://github.com/jennysivapalan/xsbt-cucumber-plugin/commit/e78c622c11a37d6493b3b9deb2c1b127a18c31a8

**Comment by tobyclemson** [comment]
Another vote for this :+1:

**Comment by nicl** [comment]
Okay so I have bumped up the version and as @skipoleschris mentioned, the tests don't work. At the moment I'm getting a very non-useful stacktrace but hopefully will get this resolved. My fork is here: https://github.com/nicl/xsbt-cucumber-plugin.

**Comment by skipoleschris** [comment]
It's a bug in the pretty formatter in the version of gherkin that's shipped with 1.1.3.  It's been fixed for the next version. I managed to get tests running by removing the --format pretty command line options when calling cucumber, but then you don't get any test output.

Wonder if forcing a newer version of gherkin might help  

Regards,
Chris 

Chris Turner

**Comment by nicl** [comment]
Hi @skipoleschris thanks for the info. It does indeed work when I remove pretty printing. Do you know if there an issue for the Gherkin project for this bug, or for Cucumber-JVM? If not, I'm happy to raise it.

I'm happy to help codewise as long as I know what is wrong/where I can help.

**Comment by skipoleschris** [comment]
The issue has already been raised and fixed on gherkin, should be in the next release. 

Chris Turner

**Comment by nicl** [comment]
Hi Chris, that's great to know. Do you know when this release will be or is there an issue queue you can point me to? Even if not, that's good to know as I'm currently writing several tests and I'd like to use DataTables but if it is going to be a while I'll find a workaround.

I've had a look on the Cucumber JVM repo and the delay between releases seems to vary quite a lot. I couldn't see any info on when the next release would be.

Thanks.

ps. for anyone else who wants to use DataTables, at the moment my hack around this is to pass DataTables as doc strings and then parse them into a usable format. The specific function I've written is https://gist.github.com/nicl/5541327 . It probably doesn't provide useful errors if passed an incorrectly formatted string though.

**Comment by skipoleschris** [comment]
New 0.8.0 release upgrades to cucumber 1.1.4
